[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[project]
name = "te-cogui"
version = "1.0.0"
description = "TE Case Manager and other tools"
authors = [
    {name = "Will Koester", email = "wikoeste@cisco.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask",
    "render_template",
    "request,redirect",
    "session",
    "url_for",
    "send_from_directory",
    "flash",
    "jsonify",
    "werkzeug.utils",
    "re",
    "json",
    "ipaddress",
    "os","datetime",
    "itertools",
    "csv",
    "flask_login",
    "pandas",
    "threading"
]



[project.scripts]
liono = server.py